"""init

Revision ID: 286d24eca08c
Revises: 
Create Date: 2023-05-11 12:47:43.179553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286d24eca08c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_my_address', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_my_address')

    # ### end Alembic commands ###
