"""change field name

Revision ID: 50256e008e09
Revises: 286d24eca08c
Create Date: 2023-05-11 17:03:08.801048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50256e008e09'
down_revision = '286d24eca08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_my_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_my_address', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
